openapi: 3.0.1
info:
  title: Keeper Service API
  description: Keeper Service is used to work with Products
  version: 1.0.0
servers:
  - url: 'http://localhost:8081/api/v1/'

paths:

  /products:

    get:
      summary: Returns all products
      responses:
        '200':
          description: Successfully returned products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
      tags:
        - ProductController

    post:
      summary: Adds the product
      parameters:
        - name: product
          description: The product to add
          in: query
          required: true
          schema:
            type: object
      responses:
        '200':
          description: Successfully added product
          content:
            application/json:
              schema:
                type: object
      tags:
        - ProductController

  /products/{productId}:

    get:
      summary: Returns the product with given productId
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully returned product
          content:
            application/json:
              schema:
                type: object
      tags:
        - ProductController

    delete:
      summary: Deletes the product with given productId
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted product
          content:
            application/json:
              schema:
                type: boolean
      tags:
        - ProductController

    put:
      summary: Updates the product with given productId
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully updated product
          content:
            application/json:
              schema:
                type: object
      tags:
        - ProductController

  /products/{productCode}:

    get:
      summary: Returns list of products with given productCode
      parameters:
        - name: productCode
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully returned list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
      tags:
        - ProductController

    delete:
      summary: Deletes list of products with given productCode
      parameters:
        - name: productCode
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted list of products
          content:
            application/json:
              schema:
                type: boolean
      tags:
        - ProductController

    put:
      summary: Updates list of products with given productCode
      parameters:
        - name: productCode
          in: path
          required: true
          schema:
            type: string
        - name: product
          description: The product to update
          in: query
          required: true
          schema:
            type: object
      responses:
        '200':
          description: Successfully updated list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
      tags:
        - ProductController

  /products/list:

    post:
      summary: Adds list of products
      parameters:
        - name: productList
          description: The list of products to add
          in: query
          required: true
          schema:
            type: array
            items:
              type: object
      responses:
        '200':
          description: Successfully added list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
      tags:
        - ProductController

    delete:
      summary: Deletes list of products
      parameters:
        - name: productList
          description: The list of products to delete
          in: query
          required: true
          schema:
            type: array
            items:
              type: object
      responses:
        '200':
          description: Successfully deleted list of products
          content:
            application/json:
              schema:
                type: boolean
      tags:
        - ProductController